name: spacetimehopfion-env

channels:
  - conda-forge

dependencies:
  - python==3.11
  - numpy==1.26.3
  - matplotlib==3.8.2
  - scipy==1.12.0
  - scikit-image==0.22.0
  - discretisedfield==0.65.1
  - pandas==2.2.0
  - findiff==0.10.0